<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Aspire.AppHost.Sdk" Version="13.1.2" />

  <PropertyGroup Label="General">
    <OutputType>Exe</OutputType>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>a1d43a2c-e345-4da9-b866-2a39d5009e40</UserSecretsId>
  </PropertyGroup>

  <ItemGroup Label="Packages">
    <PackageReference Include="Aspire.Hosting.AppHost" />
  </ItemGroup>

  <ItemGroup Label="Projects">
    <ProjectReference Include="..\Privatekonomi.Api\Privatekonomi.Api.csproj" />
    <ProjectReference Include="..\Privatekonomi.Web\Privatekonomi.Web.csproj" />
    <ProjectReference Include="..\Privatekonomi.ServiceDefaults\Privatekonomi.ServiceDefaults.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

</Project>
