<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup Label="General">
    <UserSecretsId>eb8f9493-8e5f-4f49-95ce-0bf639dddbd5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup Label="Packages">
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup Label="Projects">
    <ProjectReference Include="..\Privatekonomi.Core\Privatekonomi.Core.csproj" />
    <ProjectReference Include="..\Privatekonomi.ServiceDefaults\Privatekonomi.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
