using System.Net;
using System.Net.Http.Json;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Moq;
using Privatekonomi.Core.Data;
using Privatekonomi.Core.Models;
using Privatekonomi.Core.Services;
using Xunit;

namespace Privatekonomi.Api.Tests;

public class BudgetAlertsControllerTests
{
    private WebApplicationFactory<Program> CreateFactory(string databaseName)
    {
        return new WebApplicationFactory<Program>()
            .WithWebHostBuilder(builder =>
            {
                builder.ConfigureServices(services =>
                {
                    // Remove the existing DbContext configuration
                    var descriptor = services.SingleOrDefault(
                        d => d.ServiceType == typeof(DbContextOptions<PrivatekonomyContext>));

                    if (descriptor != null)
                    {
                        services.Remove(descriptor);
                    }

                    // Add in-memory database for testing
                    services.AddDbContext<PrivatekonomyContext>(options =>
                    {
                        options.UseInMemoryDatabase(databaseName);
                    });
                    
                    // Add mock for ICurrentUserService (anonymous user for API tests)
                    var mockCurrentUserService = new Mock<ICurrentUserService>();
                    mockCurrentUserService.Setup(x => x.IsAuthenticated).Returns(false);
                    mockCurrentUserService.Setup(x => x.UserId).Returns((string?)null);
                    
                    // Remove existing ICurrentUserService registration and add mock
                    var currentUserDescriptor = services.SingleOrDefault(
                        d => d.ServiceType == typeof(ICurrentUserService));
                    if (currentUserDescriptor != null)
                    {
                        services.Remove(currentUserDescriptor);
                    }
                    services.AddScoped<ICurrentUserService>(_ => mockCurrentUserService.Object);
                });
            });
    }

    private async Task<(Budget budget, BudgetCategory budgetCategory, Category category)> CreateTestBudgetAsync(IServiceProvider services)
    {
        using var scope = services.CreateScope();
        var context = scope.ServiceProvider.GetRequiredService<PrivatekonomyContext>();

        // CategoryId is auto-generated by the database when using Entity Framework
        var category = new Category
        {
            Name = "Test Category",
            Color = "#FF0000",
            IsSystemCategory = false,
            CreatedAt = DateTime.UtcNow
        };
        context.Categories.Add(category);
        await context.SaveChangesAsync();

        var budget = new Budget
        {
            Name = "Test Budget",
            StartDate = new DateTime(2025, 1, 1),
            EndDate = new DateTime(2025, 1, 31),
            Period = BudgetPeriod.Monthly,
            CreatedAt = DateTime.UtcNow,
            ValidFrom = DateTime.UtcNow
        };
        context.Budgets.Add(budget);
        await context.SaveChangesAsync();

        var budgetCategory = new BudgetCategory
        {
            BudgetId = budget.BudgetId,
            CategoryId = category.CategoryId,
            PlannedAmount = 5000m
        };
        context.BudgetCategories.Add(budgetCategory);
        await context.SaveChangesAsync();

        return (budget, budgetCategory, category);
    }

    [Fact]
    public async Task GetActiveAlerts_ReturnsOkResult()
    {
        // Arrange
        var databaseName = Guid.NewGuid().ToString();
        await using var factory = CreateFactory(databaseName);
        var client = factory.CreateClient();

        // Act
        var response = await client.GetAsync("/api/budget-alerts");

        // Assert
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
    }

    [Fact]
    public async Task GetAlertsForBudget_ReturnsOkResult()
    {
        // Arrange
        var databaseName = Guid.NewGuid().ToString();
        await using var factory = CreateFactory(databaseName);
        var client = factory.CreateClient();
        var (budget, _, _) = await CreateTestBudgetAsync(factory.Services);

        // Act
        var response = await client.GetAsync($"/api/budget-alerts/budget/{budget.BudgetId}");

        // Assert
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
    }

    [Fact]
    public async Task GetAlertsForCategory_ReturnsOkResult()
    {
        // Arrange
        var databaseName = Guid.NewGuid().ToString();
        await using var factory = CreateFactory(databaseName);
        var client = factory.CreateClient();
        var (budget, _, category) = await CreateTestBudgetAsync(factory.Services);

        // Act
        var response = await client.GetAsync($"/api/budget-alerts/budget/{budget.BudgetId}/category/{category.CategoryId}");

        // Assert
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
    }

    [Fact]
    public async Task CheckAllBudgets_ReturnsOkResult()
    {
        // Arrange
        var databaseName = Guid.NewGuid().ToString();
        await using var factory = CreateFactory(databaseName);
        var client = factory.CreateClient();

        // Act
        var response = await client.PostAsync("/api/budget-alerts/check", null);

        // Assert
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
    }

    [Fact]
    public async Task CheckBudget_ReturnsOkResult()
    {
        // Arrange
        var databaseName = Guid.NewGuid().ToString();
        await using var factory = CreateFactory(databaseName);
        var client = factory.CreateClient();
        var (budget, _, _) = await CreateTestBudgetAsync(factory.Services);

        // Act
        var response = await client.PostAsync($"/api/budget-alerts/check/{budget.BudgetId}", null);

        // Assert
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
    }

    [Fact]
    public async Task GetCategoryUsage_ReturnsOkResult()
    {
        // Arrange
        var databaseName = Guid.NewGuid().ToString();
        await using var factory = CreateFactory(databaseName);
        var client = factory.CreateClient();
        var (budget, _, category) = await CreateTestBudgetAsync(factory.Services);

        // Act
        var response = await client.GetAsync($"/api/budget-alerts/budget/{budget.BudgetId}/category/{category.CategoryId}/usage");

        // Assert
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
    }

    [Fact]
    public async Task GetSettings_ReturnsOkResult()
    {
        // Arrange
        var databaseName = Guid.NewGuid().ToString();
        await using var factory = CreateFactory(databaseName);
        var client = factory.CreateClient();

        // Act
        var response = await client.GetAsync("/api/budget-alerts/settings");

        // Assert
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
    }

    [Fact]
    public async Task GetActiveFreezes_ReturnsOkResult()
    {
        // Arrange
        var databaseName = Guid.NewGuid().ToString();
        await using var factory = CreateFactory(databaseName);
        var client = factory.CreateClient();

        // Act
        var response = await client.GetAsync("/api/budget-alerts/freeze");

        // Assert
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
    }

    [Fact]
    public async Task IsBudgetFrozen_ReturnsOkResult()
    {
        // Arrange
        var databaseName = Guid.NewGuid().ToString();
        await using var factory = CreateFactory(databaseName);
        var client = factory.CreateClient();
        var (budget, _, _) = await CreateTestBudgetAsync(factory.Services);

        // Act
        var response = await client.GetAsync($"/api/budget-alerts/freeze/budget/{budget.BudgetId}");

        // Assert
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        var isFrozen = await response.Content.ReadFromJsonAsync<bool>();
        Assert.False(isFrozen);
    }
}
