using Microsoft.Extensions.DependencyInjection;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Privatekonomi.Api.Tests.Infrastructure;
using Privatekonomi.Core.Data;
using Privatekonomi.Core.Models;
using System.Net;
using System.Net.Http.Json;

namespace Privatekonomi.Api.Tests;

[TestClass]
public class BudgetAlertsControllerTests
{
    private async Task<(Budget budget, BudgetCategory budgetCategory, Category category)> CreateTestBudgetAsync(IServiceProvider services)
    {
        using var scope = services.CreateScope();
        var context = scope.ServiceProvider.GetRequiredService<PrivatekonomyContext>();

        // CategoryId is auto-generated by the database when using Entity Framework
        var category = new Category
        {
            Name = "Test Category",
            Color = "#FF0000",
            IsSystemCategory = false,
            CreatedAt = DateTime.UtcNow
        };
        context.Categories.Add(category);
        await context.SaveChangesAsync();

        var budget = new Budget
        {
            Name = "Test Budget",
            StartDate = new DateTime(2025, 1, 1),
            EndDate = new DateTime(2025, 1, 31),
            Period = BudgetPeriod.Monthly,
            CreatedAt = DateTime.UtcNow,
            ValidFrom = DateTime.UtcNow
        };
        context.Budgets.Add(budget);
        await context.SaveChangesAsync();

        var budgetCategory = new BudgetCategory
        {
            BudgetId = budget.BudgetId,
            CategoryId = category.CategoryId,
            PlannedAmount = 5000m
        };
        context.BudgetCategories.Add(budgetCategory);
        await context.SaveChangesAsync();

        return (budget, budgetCategory, category);
    }

    [TestMethod]
    public async Task GetActiveAlertsReturnsOkResult()
    {
        // Arrange
        var databaseName = Guid.NewGuid().ToString();
        await using var factory = new ApiWebApplicationFactory(databaseName);
        var client = factory.CreateClient();

        // Act
        var response = await client.GetAsync("/api/budget-alerts");

        // Assert
        Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
    }

    [TestMethod]
    public async Task GetAlertsForBudgetReturnsOkResult()
    {
        // Arrange
        var databaseName = Guid.NewGuid().ToString();
        await using var factory = new ApiWebApplicationFactory(databaseName);
        var client = factory.CreateClient();
        var (budget, _, _) = await CreateTestBudgetAsync(factory.Services);

        // Act
        var response = await client.GetAsync($"/api/budget-alerts/budget/{budget.BudgetId}");

        // Assert
        Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
    }

    [TestMethod]
    public async Task GetAlertsForCategoryReturnsOkResult()
    {
        // Arrange
        var databaseName = Guid.NewGuid().ToString();
        await using var factory = new ApiWebApplicationFactory(databaseName);
        var client = factory.CreateClient();
        var (budget, _, category) = await CreateTestBudgetAsync(factory.Services);

        // Act
        var response = await client.GetAsync($"/api/budget-alerts/budget/{budget.BudgetId}/category/{category.CategoryId}");

        // Assert
        Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
    }

    [TestMethod]
    public async Task CheckAllBudgetsReturnsOkResult()
    {
        // Arrange
        var databaseName = Guid.NewGuid().ToString();
        await using var factory = new ApiWebApplicationFactory(databaseName);
        var client = factory.CreateClient();

        // Act
        var response = await client.PostAsync("/api/budget-alerts/check", null);

        // Assert
        Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
    }

    [TestMethod]
    public async Task CheckBudgetReturnsOkResult()
    {
        // Arrange
        var databaseName = Guid.NewGuid().ToString();
        await using var factory = new ApiWebApplicationFactory(databaseName);
        var client = factory.CreateClient();
        var (budget, _, _) = await CreateTestBudgetAsync(factory.Services);

        // Act
        var response = await client.PostAsync($"/api/budget-alerts/check/{budget.BudgetId}", null);

        // Assert
        Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
    }

    [TestMethod]
    public async Task GetCategoryUsageReturnsOkResult()
    {
        // Arrange
        var databaseName = Guid.NewGuid().ToString();
        await using var factory = new ApiWebApplicationFactory(databaseName);
        var client = factory.CreateClient();
        var (budget, _, category) = await CreateTestBudgetAsync(factory.Services);

        // Act
        var response = await client.GetAsync($"/api/budget-alerts/budget/{budget.BudgetId}/category/{category.CategoryId}/usage");

        // Assert
        Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
    }

    [TestMethod]
    public async Task GetSettingsReturnsOkResult()
    {
        // Arrange
        var databaseName = Guid.NewGuid().ToString();
        await using var factory = new ApiWebApplicationFactory(databaseName);
        var client = factory.CreateClient();

        // Act
        var response = await client.GetAsync("/api/budget-alerts/settings");

        // Assert
        Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
    }

    [TestMethod]
    public async Task GetActiveFreezesReturnsOkResult()
    {
        // Arrange
        var databaseName = Guid.NewGuid().ToString();
        await using var factory = new ApiWebApplicationFactory(databaseName);
        var client = factory.CreateClient();

        // Act
        var response = await client.GetAsync("/api/budget-alerts/freeze");

        // Assert
        Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
    }

    [TestMethod]
    public async Task IsBudgetFrozenReturnsOkResult()
    {
        // Arrange
        var databaseName = Guid.NewGuid().ToString();
        await using var factory = new ApiWebApplicationFactory(databaseName);
        var client = factory.CreateClient();
        var (budget, _, _) = await CreateTestBudgetAsync(factory.Services);

        // Act
        var response = await client.GetAsync($"/api/budget-alerts/freeze/budget/{budget.BudgetId}");

        // Assert
        Assert.AreEqual(HttpStatusCode.OK, response.StatusCode);
        var isFrozen = await response.Content.ReadFromJsonAsync<bool>();
        Assert.IsFalse(isFrozen);
    }
}
