<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="General">
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup Label="Packages">
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <!--<PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />-->
    <PackageReference Include="Moq" />
    <PackageReference Include="MSTest" />
    <PackageReference Include="MSTest.TestFramework" />
    <PackageReference Include="MSTest.TestAdapter" />
  </ItemGroup>

  <ItemGroup Label="GlobalUsings">
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup Label="Projects">
    <ProjectReference Include="..\..\src\Privatekonomi.Core\Privatekonomi.Core.csproj" />
  </ItemGroup>

</Project>
